---
title: "Scientific papers on 'Taper functions'"
author: "prof. Roberto Scotti ^[NuoroForestrySchool - scotti@uniss.it]"
date: "`r format(Sys.time(), '%d %b %Y')`"
output: pdf_document
---

   
```{r open DBs, echo=FALSE, results='hide'}
# https://docs.google.com/spreadsheets/d/1Z6LpZgBogxYrTimiBjFcCMam7gp8-YNeH2sdAiNf8i4/edit#gid=0 
library(tidyverse)
library(googlesheets)
suppressMessages(library(dplyr))
sbib <- 
  "https://docs.google.com/spreadsheets/d/1R-2vIdEAi1Kc6qo0hriMFIHZ8QeJSu-mPJDHJsecLDI/edit#gid=948369352" %>% 
  extract_key_from_url() %>%
  gs_key() %>%
  gs_read(ws = "Analysis") %>%
  arrange(ArticleID, line)


library(RefManageR)
zbib <- ReadZotero(group = "130380", 
                   .params = list(collection = "MYKE5653"))
# NoCite(zbib)
# PrintBibliography(zbib, .opts = list(bib.style = "authoryear", style = "markdown"))

```
# Introduction

## 2018 Forest Inventory course - Collective students' work
Students, as homework, were asked to search for scientific papers presenting 'taper functions' and to compile a collective Rmarkdown document shared using GIT.  
Rearranging their work, this document lists their findings.  

# Results of students' searches

```{r results='asis', echo=FALSE}
#library(knitr)
#library(kableExtra)
library(xtable)

eq.dir <- "Equations"
nart <- length(unique(sbib$ArticleID))

#for(i in 1:nart) {
for(i in 1) {
  zid <- sbib$value[sbib$ArticleID==i &
                    sbib$field=="Zotero.ID"]
#  cat(paste0("\n\n\n## Article ID: ", i,
#             "                  ___", cite(zid, zbib ),"___"))
#  cat("\n*** *", zbib$title[[zid]], "* ***")
  sbib %>%
    as.tibble() %>%
    filter(ArticleID == i) %>%
    select(field, value) %>%
    filter(!field %in% 
             c("## ArticleID", "Zotero.ID")) %>%
    xtable(align = c("p{0cm}" ,"p{3cm}" , "p{8cm}" )) %>%
#    kable("latex", booktabs = T) %>%
#    column_spec(1:2, width = "6cm") %>%
#    kable_styling(latex_options="scale_down") %>%
#    kable_styling(full_width = F) %>%
#    column_spec(1, width = c("2cm")) %>%
    print(include.rownames=FALSE)
#    print()
}
```


# References
```{r results='asis', echo=FALSE}
#PrintBibliography(zbib, .opts = list(bib.style = "authoryear", style = "markdown"))
# rmarkdown::render("AnalysisOfTaperFunctionsStrutures.Rmd")

```
